### ISSUE TITLE
Installing board definition through IDE option fails

### ISSUE THREAD

**Issue by giplt** [meetjestad/mjs_boards#1]
Adding the meetjestad board definition through the 'Additional board manager URLs' menu option doesn't seem to work in Arduino 1.8.7 IDE for Windows.

**Comment by per1234** [comment]
It works for me. Please provide a detailed explanation of what you mean by "doesn't seem to work".

**Comment by giplt** [comment]
On someone's Windows laptop I tried installing the board definition by adding a URL to the board definition in the preferences menu as instructed in README.md, but the board didn't show op under Tools > board in the menu. Restarting Arduino didn't help either. Manual install by unzipping the defs in the sketchbook/hardware folder worked however. Same happened on another Windows laptop we tried. Arduino versions were 1.8.7 and 1.8.8 respectively. Didn't have time to explore further and have no access to Windows machines myself. So there _might_ be an issue here.

**Comment by per1234** [comment]
Did you do the rest of the installation steps, as [described in the readme](https://github.com/meetjestad/mjs_boards#meet-je-stad-arduino-board-definitions)?:
> - Close the preferences, and open Tools -> Board -> Boards Manager...
> - Find the "Meet je stad! AVR Boards" in the list, and click Install

**Comment by matthijskooijman** [comment]
I'm closing this, probably PEBCAK :-)
